### ISSUE TITLE
Strange Behavior with `get_significant_results()` - Minor Impact

### ISSUE THREAD

**Issue by AGoum** [nexomis/fctBio#3]
When calling the `get_significant_results()` method (from `NestedEnrich {fctBio}`), the function seems to not return any results immediately. This issue appears to be related to memory handling, but it does not seem to affect the usability or functionality of the method.

It doesn’t impact the functionality of the method as the results are correctly obtained after some operations or re-accessing. However, this might be confusing for users who expect immediate results. It would be beneficial to **document this behavior in the method’s documentation** to clarify the situation for users.

#### Initial Call Behavior:
The above calls return nothing initially. There is no output displayed.
```
> nested_enrich$get_significant_results()
> nested_enrich$get_significant_results()
> nested_enrich$get_significant_results()
> 
# Returns nothing
```

#### Repeated Calls:
When calling get_significant_results() and assigning the result to a variable, the second attempt to access the variable correctly displays the results:
```
> a <- nested_enrich$get_significant_results()
> a
> 
# Still returns nothing
> a
# Displays results correctly
```

#### Time Delay Test:
Adding a time delay between calls does not resolve the issue:
```
> a <- nested_enrich$get_significant_results()
> Sys.sleep(100)
> a
> 
# Still returns nothing
```

#### Access After Applying a Function:
Applying any function or method to the result variable immediately shows the content:
```
> a <- nested_enrich$get_significant_results()
> head(a)
# Displays results correctly
> head(nested_enrich$get_significant_results())
# Displays results correctly
```

#### Memory-Intensive Operations:
The execution of a memory-intensive operation seems to make the result accessible from the first call.
```
> nested_enrich_bis <- nested_enrich$clone()
> a <- nested_enrich$get_significant_results()
> b <- nested_enrich_bis$build_cluster_summary_table()
> a
# Displays results correctly after memory-intensive operation
```

**Comment by jfouret** [comment]
When an object is computation-intensive for its representation, I tend to use the invisible function to return it to avoid the freezing of the session if the memory is limited. 

The object is indeed temporarily invisible and anyway represented is explicitely asked.
