### ISSUE TITLE
Some bugs in fctBio's basic functions

### ISSUE THREAD

**Issue by AGoum** [nexomis/fctBio#4]
- [ ] `write_xlsx()`  method of `NestedEnrich` class produce partial xlsx results with only sheet 'dereg_GO', 'up_GO', 'down_GO' and 'dereg_RC' (missing: 'upRC', 'down_RC', 'dereg_KW', 'up_KW', 'down_KW')

 - [ ] `write_cluster_summary = TRUE`  on `write_xlsx()`  of `NestedEnrich` class make an error:
```
> nested_enrich$write_xlsx(output_folder = "fctbio_summaryTrue_20pc/", write_cluster_summary = TRUE)
Error in data.table::rbindlist(lapply(unique(private$results$group), function(group_in) { : 
  Item 2 has 3 columns, inconsistent with item 1 which has 2 columns. To fill missing columns use fill=TRUE.
```
 - [ ] Exactly same error when calling method `count_gene_per_cluster()`  :
```
> nested_enrich$count_gene_per_cluster()
Error in data.table::rbindlist(lapply(unique(private$results$group), function(group_in) { : 
  Item 2 has 3 columns, inconsistent with item 1 which has 2 columns. To fill missing columns use fill=TRUE.
```
 - [ ] It isn't tested with the same dataset, so it may be false, but the call to 'pvclust' in 'parrale' mode via the `build_and_set_hclust()` method seems to require extremely more resources than before (a need to be verified!).

**Comment by jfouret** [comment]
No context and not reproducible with test data
